### PR TITLE
Release test

### PR DESCRIPTION
**Pull request by niklio**

### CODE REVIEW

**Review by emattson — CHANGES_REQUESTED** [review]
Release test doesn't actually do any kind of test to make sure it released. Can we do a pip lookup or something to make sure the upload was successful? 

Also what is the point of release-test as a branch?

**Comment by niklio** [comment]
Release test push

**Comment by niklio** [comment]
Release test pushes the build archive to https://test.pypi.org. If the push fails, twine will throw a nonzero exit code.
Here's an example of a failed build: https://circleci.com/gh/tetrachrome/aiokinesis/96
Here's a successful build: https://circleci.com/gh/tetrachrome/aiokinesis/99

**Review by emattson — DISMISSED** [review]
LGTM. Let's get some kind of doc with enough detail someone unfamiliar with this could push a hotfix

**Review by emattson — APPROVED** [review]

**Pull request merged**
